CREATE TABLE Assunto (
    codAs INT GENERATED BY DEFAULT AS IDENTITY,
    Descricao VARCHAR(20),
    PRIMARY KEY (codAs)
);

CREATE TABLE Autor (
    CodAu INT GENERATED BY DEFAULT AS IDENTITY,
    Nome VARCHAR(40),
    PRIMARY KEY (CodAu)
);

CREATE TABLE Livro (
    Codl INT GENERATED BY DEFAULT AS IDENTITY,
    Titulo VARCHAR(40),
    Editora VARCHAR(40),
    Edicao INT,
    AnoPublicacao VARCHAR(4),
    Valor INT,
    PRIMARY KEY (Codl)
);

CREATE TABLE Livro_Assunto (
    Livro_Codl INT,
    Assunto_codAs INT,
    PRIMARY KEY (Livro_Codl, Assunto_codAs),
    FOREIGN KEY (Livro_Codl) REFERENCES Livro(Codl),
    FOREIGN KEY (Assunto_codAs) REFERENCES Assunto(codAs)
);

CREATE TABLE Livro_Autor (
    Livro_Codl INT,
    Autor_CodAu INT,
    PRIMARY KEY (Livro_Codl, Autor_CodAu),
    FOREIGN KEY (Livro_Codl) REFERENCES Livro(Codl),
    FOREIGN KEY (Autor_CodAu) REFERENCES Autor(CodAu)
);